micronaut:
  application:
    name: keyManagerGrpc

datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_UPDATE
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update